CREATE TABLE GUEST_MASTER (
    GUEST_ID           NUMBER PRIMARY KEY,
    FIRST_NAME         VARCHAR2(50),
    LAST_NAME          VARCHAR2(50),
    GENDER             VARCHAR2(10),
    DATE_OF_BIRTH      DATE,
    EMAIL              VARCHAR2(100),
    PHONE_NUMBER       VARCHAR2(15),
    ADDRESS_LINE1      VARCHAR2(150),
    ADDRESS_LINE2      VARCHAR2(150),
    CITY               VARCHAR2(50),
    STATE              VARCHAR2(50),
    COUNTRY            VARCHAR2(50),
    ID_PROOF_TYPE      VARCHAR2(20),
    ID_PROOF_NUMBER    VARCHAR2(30),
    REGISTRATION_DATE  DATE
);

CREATE TABLE STAYS (
    STAY_ID NUMBER,
    GUEST_ID NUMBER,
    ROOM_ID NUMBER,
    CHECKIN_DATETIME TIMESTAMP,
    CHECKOUT_DATETIME TIMESTAMP,
    BOOKING_SOURCE VARCHAR2(20),
    NUMBER_OF_GUESTS NUMBER,
    ROOM_RATE NUMBER,
    EXTRA_CHARGES NUMBER,
    DISCOUNT NUMBER,
    TOTAL_AMOUNT NUMBER,
    PAYMENT_MODE VARCHAR2(20),
    STATUS VARCHAR2(20),
    LAST_UPDATED DATE
);
CREATE TABLE ROOM_MASTER (
    ROOM_ID            NUMBER PRIMARY KEY,
    ROOM_TYPE          VARCHAR2(50),
    FLOOR_NUMBER       NUMBER,
    BED_TYPE           VARCHAR2(20),
    BASE_RATE          NUMBER,
    ROOM_STATUS        VARCHAR2(20),
    MAX_OCCUPANCY      NUMBER,
    AMENITIES          VARCHAR2(200),
    LAST_CLEANED_DATE  DATE
);
select * from guest_master;
select * from room_master;
select * from guest_master

CREATE OR REPLACE PROCEDURE PRC_DAILY_HOTEL_REPORT (
    P_REPORT_DATE IN DATE DEFAULT TRUNC(SYSDATE)
)
AS
    V_TOTAL_CHECKINS   NUMBER;
    V_TOTAL_CHECKOUTS  NUMBER;
    V_OCCUPIED_ROOMS   NUMBER;
    V_TOTAL_REVENUE    NUMBER(12,2);
BEGIN
    SELECT COUNT(*)
    INTO V_TOTAL_CHECKINS
    FROM STG_GUEST_STAY
    WHERE TRUNC(CHECKIN_DATETIME) = TRUNC(P_REPORT_DATE);

    SELECT COUNT(*)
    INTO V_TOTAL_CHECKOUTS
    FROM STG_GUEST_STAY
    WHERE CHECKOUT_DATETIME IS NOT NULL
      AND TRUNC(CHECKOUT_DATETIME) = TRUNC(P_REPORT_DATE);

    SELECT COUNT(DISTINCT ROOM_ID)
    INTO V_OCCUPIED_ROOMS
    FROM STG_GUEST_STAY
    WHERE TRUNC(CHECKIN_DATETIME) <= TRUNC(P_REPORT_DATE)
      AND (CHECKOUT_DATETIME IS NULL OR TRUNC(CHECKOUT_DATETIME) >= TRUNC(P_REPORT_DATE));

    SELECT NVL(SUM(TOTAL_AMOUNT),0)
    INTO V_TOTAL_REVENUE
    FROM STG_GUEST_STAY
    WHERE TRUNC(CHECKIN_DATETIME) = TRUNC(P_REPORT_DATE);

    DELETE FROM DAILY_HOTEL_REPORT
    WHERE TRUNC(REPORT_DATE) = TRUNC(P_REPORT_DATE);

    INSERT INTO DAILY_HOTEL_REPORT (
        REPORT_DATE,
        TOTAL_CHECKINS,
        TOTAL_CHECKOUTS,
        OCCUPIED_ROOMS,
        TOTAL_REVENUE
    )
    VALUES (
        TRUNC(P_REPORT_DATE),
        V_TOTAL_CHECKINS,
        V_TOTAL_CHECKOUTS,
        V_OCCUPIED_ROOMS,
        V_TOTAL_REVENUE
    );

    COMMIT;
END;
/